app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('about/', views.about),
    path('contact/', views.contact),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.all_posts, name='list'),
    path('new-post/', views.post_new, name='new-post'),
    path('<slug:slug>', views.post_page, name='page'),
    path('search/', views.search_posts, name='search-view'),
    path('filter/', views.filter_posts, name='filter-view'),
    path('<slug:slug>/new-comment/', views.comment_new, name='new-comment'),
    path('<slug:slug>/edit/', views.post_edit_view, name='edit-post'),
    path('<slug:slug>/delete/', views.post_delete_view, name='delete-post'),
]

app/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('update-profile/', views.update_profile_view, name='update-profile'),
    path('profile/<str:username>/', views.profile_view, name='profile'),
    path('user-posts/', views.user_posts_view, name='user-posts'),

]

app/posts/models.py
from django.db import models
from django.contrib.auth.models import User

CATEGORY_CHOICES = [
    ('NAT', 'Nature'),
    ('TECH', 'Technology'),
    ('LIFE', 'Lifestyle'),
    ('FIN', 'Finance'),
    ('EDU', 'Education'),
    ('ENT', 'Entertainment'),
    ('HEAL', 'Health'),
    ('FOOD', 'Food & Drink'),
    ('TRVL', 'Travel'),
    ('SPT', 'Sports'),
    ('BUS', 'Business'),
    ('SCI', 'Science'),
    ('POL', 'Politics'),
    ('ART', 'Art & Culture'),
    ('MUS', 'Music'),
    ('MOV', 'Movies & TV'),
    ('AUTO', 'Automotive'),
    ('DIY', 'DIY & Crafts'),
    ('FASH', 'Fashion'),
    ('GAM', 'Gaming'),
    ('PETS', 'Pets'),
    ('PHOT', 'Photography'),
    ('HOME', 'Home & Garden'),
    ('REL', 'Religion & Spirituality'),
    ('OTR', 'Other')
]

# Create your models here.
class Post(models.Model):
    # Define the available categories

    title = models.CharField(max_length=50)
    body = models.TextField()
    slug = models.SlugField()
    category = models.CharField(default='OTR', max_length=4, choices=CATEGORY_CHOICES)
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='../static/assets/fallback.webp', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    
    class Meta:
        ordering = ['-date']
    
    def __str__(self) -> str:
        return self.title
    
    @staticmethod
    def convert_name_to_code(name):
        for code, category in CATEGORY_CHOICES:
            if category == name:
                return code
        return 'OTR'
    
    def convert_code_to_name(code):
        for category, name in CATEGORY_CHOICES:
            if category == code:
                return name
        return 'Other'
    

class Comment(models.Model):
    body = models.TextField(default='')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, default=None)
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.body

app/users/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_image = models.ImageField(default='../static/assets/user-fallback.webp', blank=True)
    bio = models.TextField(max_length=500, blank=True, default='')
    address = models.CharField(max_length=100, blank=True, default='')
    phone = models.CharField(max_length=20, blank=True, default='')
    
    
    def __str__(self):
        return self.user.username

# Create automatically the user profile when a new user is created 
# (the fields will be added by the user in his user's modification page)

def create_profile(sender, instance, created, **kwargs):
    if created:
        user_profile = UserProfile(user=instance)
        user_profile.save()
        
# Connect the signal to the function
post_save.connect(create_profile, sender=User)

app/users/forms.py
from django import forms
from .models import UserProfile

class UserInfoForm(forms.ModelForm):
    
    profile_image = forms.ImageField(
        required=False, 
        label='', 
        widget=forms.FileInput(attrs={'class': 'form-control-file'})
        )
    
    bio = forms.CharField(max_length=500)
    address = forms.CharField(max_length=100)
    phone = forms.CharField(max_length=20)
    
    class Meta:
        model = UserProfile
        fields = ( 'profile_image', 'bio', 'address', 'phone')

app/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from .forms import UserInfoForm
from .models import UserProfile
from django.contrib import messages
from posts.models import Post
from django.contrib.auth.decorators import login_required

'''
    Create a logger for the views
'''
import logging

logging_path = './logs/users_views.log'

logging.basicConfig(
    level=logging.DEBUG,
    format='%(asctime)s [%(levelname)s] %(message)s',
    datefmt='%m/%d/%Y %H:%M:%S',
    filename=logging_path,
    )

# Create your views here.
def register_view(request):
    # If the request method is POST, it means the form has been submitted
    if(request.method == 'POST'):
        form = UserCreationForm(request.POST)
        if form.is_valid():
            login(request, form.save())
            if "next" in request.POST:
                return redirect(request.POST.get('next'))
            return redirect('posts:list')
    # If the request method is GET, it means the form has not been submitted
    else:
        form = UserCreationForm()
    
    
    return render(request, 'users/register.html', {'form': form})

# login view
def login_view(request):
    if(request.method == 'POST'):
        form = AuthenticationForm(data=request.POST)
        if(form.is_valid()):
            # Login logic
            login(request, form.get_user())
            return redirect('posts:list')
    else:
        form = AuthenticationForm()
    
    return render(request, 'users/login.html', {'form': form})


# logout view
def logout_view(request):
    if(request.method == 'POST'):
        logout(request)
        return redirect('/')


def update_profile_view(request):
    logging.debug('Update profile view')
    logging.info(f'Request: {request}')
    if request.user.is_authenticated:
        try:
            current_user = UserProfile.objects.get(user=request.user)
            logging.debug(f'Current user: {current_user}')
        except UserProfile.DoesNotExist:
            logging.error('UserProfile does not exist.')
            messages.error(request, "UserProfile does not exist.")
            logging.debug('Redirecting to login')
            return redirect('users:login')

        if request.method == 'POST':
            logging.debug('Initializing form for POST request')
            # Include request.FILES for file uploads
            form = UserInfoForm(request.POST, request.FILES, instance=current_user)
            if form.is_valid():
                logging.debug('Form is valid')
                form.save()
                logging.debug('Profile updated successfully')
                messages.success(request, 'Profile updated successfully')
                logging.debug('Redirecting to /')
                return redirect('/')
        else:
            # Initialize the form with the instance but without POST data for GET requests
            logging.debug('Initializing form for GET request')
            form = UserInfoForm(instance=current_user)

        logging.debug('Rendering update_profile.html')
        return render(request, 'users/update_profile.html', {'form': form})
    else:
        logging.error('User is not authenticated')
        messages.error(request, 'You must be logged in to update your profile')
        logging.debug('Redirecting to login')
        return redirect('users:login')
    
    
def profile_view(request, username):
    logging.info(f'Profile view for {username}')
    logging.debug(f'Request: {request}')
    try:
        userprofile = UserProfile.objects.get(user__username=username)
        posts = Post.objects.filter(author=userprofile.user)
        logging.debug(f'User: {userprofile}')
    except UserProfile.DoesNotExist:
        logging.error('UserProfile does not exist.')
        messages.error(request, "UserProfile does not exist.")
        logging.debug('Redirecting to /')
        return redirect('/')
    
    logging.debug(f'Rendering user {userprofile.user}')
    return render(request, 'users/user_profile.html', {'userprofile': userprofile, 'posts': posts})


@login_required(login_url="/users/login/")
def user_posts_view(request):
    logging.info('Calling my_posts view')
    posts = Post.objects.filter(author=request.user)
    logging.debug('Loading Posts for user {request.user}')
    return render(request, 'users/user_posts.html', {'posts': posts})

app/users/templates/users/login.html
{% extends 'layout.html'%}
{% load crispy_forms_tags %}
{% block title%}
    Login
{% endblock %}
{% block content %}
<div class="container py-4">
    <div class="row d-flex justify-content-center">
        <div class="col-md-8 col-xl-6">
            <div class="card px-5 py-5">
                <h1 class="h3 mb-3 fw-normal">Login</h1>
                <form 
                class="row g-3"
                action="/users/login/" 
                method="POST">
                    {% csrf_token %}
                    {{ form | crispy }}
                    {% if request.GET.next %}
                        <input type="hidden" name="next" value="{{ request.GET.next }}">
                    {% endif %}
                    <button type="submit" class="btn btn-dark me-2 w-100 py-2">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>   
{% endblock %}

app/users/templates/users/profile.html
{% extends 'layout.html'%}
{% load crispy_forms_tags %}
{% block title%}
    Login
{% endblock %}
{% block content %}
<h1>Profile</h1>
<div class="container py-4">
    <div class="row d-flex justify-content-center">
        <div class="col-md-8 col-xl-6">
            <div class="card px-5 py-5">
                <h1 class="h3 mb-3 fw-normal">Login</h1>
                <form 
                class="row g-3"
                action="" 
                method="POST">
                    {% csrf_token %}
                    {{ form | crispy }}
                    {% if request.GET.next %}
                        <input type="hidden" name="next" value="{{ request.GET.next }}">
                    {% endif %}
                    <button type="submit" class="btn btn-dark me-2 w-100 py-2">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>   
{% endblock %}

app/users/templates/users/register.html
{% extends 'layout.html'%}
{% load crispy_forms_tags %}
{% block title%}
    Register a New User
{% endblock %}
{% block content %}
<div class="container py-4">
    <div class="row d-flex justify-content-center">
        <div class="col-md-8 col-xl-6">
            <div class="card px-5 py-5">
                <h1 class="h3 mb-3 fw-normal">Register a New User</h1>
                <form 
                class="row g-1"
                action="/users/register/" 
                method="POST">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <button type="submit" class="btn btn-dark me-2 w-100 py-2">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/users/templates/users/update_profile.html
{% extends 'layout.html'%}
{% load crispy_forms_tags %}
{% block title%}
    Update User Info
{% endblock %}
{% block content %}
<div class="container py-4">
    <div class="row d-flex justify-content-center">
        <div class="col-md-8 col-xl-6">
            <div class="card px-5 py-5">
                <h1 class="h3 mb-3 fw-normal text-center">Update Profile Info</h1>
                <form 
                class="row g-3"
                action="{% url 'users:update-profile' %}" 
                method="POST"
                enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <button type="submit" class="btn btn-dark me-2 py-2">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>   
{% endblock %}

app/users/templates/users/user_posts.html
{% extends 'layout.html'%}
{% block title%}
    My Posts
{% endblock %}
{% block content %}
    <div class="container py-4">
        <h1 align="center">Posts List</h1>
        <div class="row" align="center">
            {% for post in posts %}
                <div class="col-xl-6 col-xxl-4 p-2">
                    <div class="card" style="width: 20rem; max-width: 100%;" align="start">
                        <img 
                        src="{{ post.banner.url }}" 
                        alt="Image description"
                        class="card-img-top"/>
                        <div class="card-body">
                            <h2 class="card-title">{{ post.title }}</h2>
                            <p class="card-text">{{ post.date }} by <strong><a href="{% url 'users:profile'  username=post.author.username %}">{{ post.author }}</a></strong></p>
                            <p class="card-text">Category: <strong>{{post.get_category_display}}</strong></p>
                            <p class="card-text text-truncate">{{ post.body }}</p>
                            <a href="{% url 'posts:page' slug=post.slug %}" class="btn btn-dark">Read Full Article</a>
                            <a href="{% url 'posts:edit-post' slug=post.slug %}" class="btn btn-warning">Edit</a>
                            <a data-bs-toggle="modal" data-bs-target="#deleteModal" class="btn btn-danger">Delete</a>
                        </div>
                    </div>
                </div>
                
                <!-- Modal -->
                <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h1 class="modal-title fs-5" id="deleteModalLabel">Confirm Deletion</h1>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                Are you sure you want to delete this post?
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                <a href="{% url 'posts:delete-post' slug=post.slug %}" class="btn btn-danger">Delete</a>
                            </div>
                        </div>
                    </div>
                </div>

            {% endfor %}
        </div>
    </div>
{% endblock %}

app/users/templates/users/user_profile.html
{% extends 'layout.html'%}
{% block title%}
    Home
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col d-flex justify-content-center align-items-center">
            <div class="card mb-3 mt-3" style="max-width: 700px;">
                <div class="row g-0">
                    <div class="col-md-4">
                        <img src="{{ userprofile.profile_image.url }}" class="img-fluid rounded-start" alt="user profile image">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">Welcome to @{{ userprofile }}'s profile!</h5>
                            <p class="card-text"><strong>First Name:</strong> {{ userprofile.user.first_name }}</p>
                            <p class="card-text"><strong>Last Name:</strong> {{ userprofile.user.last_name }}</p>
                            <p class="card-text"><strong>Email:</strong> {{ userprofile.user.email }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row" align="center">
        <h5 class="text-center">Take a look at @{{ userprofile }}'s posts!</h5>
        {% for post in posts %}
            <div class="col-xl-6 col-xxl-4 p-2">
                <div class="card" style="width: 20rem; max-width: 100%;" align="start">
                    <img 
                        src="{{ post.banner.url }}" 
                        alt="Image description"
                        class="card-img-top"/>
                        <div class="card-body">
                            <h2 class="card-title">{{ post.title }}</h2>
                            <p class="card-text">{{ post.date }} by <strong><a href="{% url 'users:profile'  username=post.author.username %}">{{ post.author }}</a></strong></p>
                            <p class="card-text">Category: <strong>{{post.get_category_display}}</strong></p>
                            <p class="card-text text-truncate">{{ post.body }}</p>
                            <a href="{% url 'posts:page' slug=post.slug %}" class="btn btn-dark">Read Full Article</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}