app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('about/', views.about),
    path('contact/', views.contact),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.all_posts, name='list'),
    path('new-post/', views.post_new, name='new-post'),
    path('<slug:slug>', views.post_page, name='page'),
    path('search/', views.search_posts, name='search-view'),
    path('filter/', views.filter_posts, name='filter-view'),
    path('<slug:slug>/new-comment/', views.comment_new, name='new-comment'),
    path('<slug:slug>/edit/', views.post_edit_view, name='edit-post'),
    path('<slug:slug>/delete/', views.post_delete_view, name='delete-post'),
]

app/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('update-profile/', views.update_profile_view, name='update-profile'),
    path('profile/<str:username>/', views.profile_view, name='profile'),
    path('user-posts/', views.user_posts_view, name='user-posts'),

]

app/posts/models.py
from django.db import models
from django.contrib.auth.models import User

CATEGORY_CHOICES = [
    ('NAT', 'Nature'),
    ('TECH', 'Technology'),
    ('LIFE', 'Lifestyle'),
    ('FIN', 'Finance'),
    ('EDU', 'Education'),
    ('ENT', 'Entertainment'),
    ('HEAL', 'Health'),
    ('FOOD', 'Food & Drink'),
    ('TRVL', 'Travel'),
    ('SPT', 'Sports'),
    ('BUS', 'Business'),
    ('SCI', 'Science'),
    ('POL', 'Politics'),
    ('ART', 'Art & Culture'),
    ('MUS', 'Music'),
    ('MOV', 'Movies & TV'),
    ('AUTO', 'Automotive'),
    ('DIY', 'DIY & Crafts'),
    ('FASH', 'Fashion'),
    ('GAM', 'Gaming'),
    ('PETS', 'Pets'),
    ('PHOT', 'Photography'),
    ('HOME', 'Home & Garden'),
    ('REL', 'Religion & Spirituality'),
    ('OTR', 'Other')
]

# Create your models here.
class Post(models.Model):
    # Define the available categories

    title = models.CharField(max_length=50)
    body = models.TextField()
    slug = models.SlugField()
    category = models.CharField(default='OTR', max_length=4, choices=CATEGORY_CHOICES)
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='../static/assets/fallback.webp', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    
    class Meta:
        ordering = ['-date']
    
    def __str__(self) -> str:
        return self.title
    
    @staticmethod
    def convert_name_to_code(name):
        for code, category in CATEGORY_CHOICES:
            if category == name:
                return code
        return 'OTR'
    
    def convert_code_to_name(code):
        for category, name in CATEGORY_CHOICES:
            if category == code:
                return name
        return 'Other'
    

class Comment(models.Model):
    body = models.TextField(default='')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, default=None)
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.body

app/posts/forms.py
from django import forms
from .models import Post, Comment

class CreatePost(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body', 'category', 'banner']

class EditPost(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body', 'category', 'banner']

class CreateComment(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']
        

app/posts/views.py
from django.shortcuts import render, redirect
from .models import Post, Comment
from .models import CATEGORY_CHOICES
from django.contrib.auth.decorators import login_required
from . import forms
from django.utils.text import slugify

from django.views.decorators.http import require_http_methods

import logging

logging_path = 'logs/posts_views.log'

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s',
    filename=logging_path,
    )

# Create your views here.
def all_posts(request):
    posts = Post.objects.all().order_by('-date')
    return render(request, 'posts/all_posts.html', {'posts': posts, 'categories': CATEGORY_CHOICES})

def post_page(request, slug):
    post = Post.objects.get(slug=slug)
    comments = Comment.objects.filter(post=post)
    logging.debug(f"Post: {post}")
    logging.debug(f"Comments: {comments}")
    return render(request, 'posts/post_page.html', { 'post': post, 'comments': comments })

@login_required(login_url="/users/login/")
def post_new(request):
    if request.method == 'POST': 
        form = forms.CreatePost(request.POST, request.FILES) 
        if form.is_valid():
            newpost = form.save(commit=False) 
            newpost.author = request.user
            newpost.slug = slugify(newpost.title)
            # Check if exist another post with the same slug
            if Post.objects.filter(slug=newpost.slug).exists():
                # If exist, add a number to the end slug
                newpost.slug = newpost.slug + '-' + str(Post.objects.filter(slug=newpost.slug).count())
            newpost.save()
            return redirect('posts:list')
    else:
        form = forms.CreatePost()
    return render(request, 'posts/post_new.html', { 'form': form })


def search_posts(request):
    if request.method == "POST":
        search_query = request.POST['search_query']
        posts = Post.objects.filter(title__contains=search_query)
        return render(request, 'posts/search_posts.html', {'query':search_query, 'posts':posts, 'categories': CATEGORY_CHOICES})
    else:
        return render(request, 'posts:list')

    
def filter_posts(request):
    if request.method == "POST":
        filter_query = request.POST.get('select_query')
        filter_query_name_to_show = Post.convert_code_to_name(filter_query)
        if filter_query == 'all':
            posts = Post.objects.all()
            filter_query_name_to_show = 'All'
        else:
            posts = Post.objects.filter(category=filter_query)
        print(f"Posts: {posts}")
        return render(request, 'posts/filter_posts.html', {'query': filter_query_name_to_show, 'posts': posts, 'categories': CATEGORY_CHOICES})
    else:
        posts = Post.objects.all()
        return render(request, 'posts/filter_posts.html', {'posts': posts})
    

@login_required(login_url="/users/login/")
def comment_new(request, slug):
    logging.info(f"Comment view on post with slug: {slug}")
    
    if request.method == 'POST':
        logging.debug(f"Comment new POST request")
        form = forms.CreateComment(request.POST)
        if form.is_valid():
            logging.debug(f'Comment form is valid')
            newcomment = form.save(commit=False)
            newcomment.author = request.user
            
            post = Post.objects.get(slug=slug)
            newcomment.post = post
            
            newcomment.save()
            logging.debug(f'Comment saved: {newcomment} saved for post {post}')
            logging.info(f'Comment saved successfully, redirecting to post {slug}')
            return redirect('posts:page', slug=slug)
        
    else:
        form = forms.CreateComment()
        logging.debug(f"Comment new GET request")
    
    return render(request, 'posts/comment_new.html', {'form': form, 'slug': slug})


def post_edit_view(request, slug):
    logging.info(f"Post edit view on post with slug: {slug}")
    # If the request was not done by the autor of the post, return 403
    if request.user != Post.objects.get(slug=slug).author:
        logging.error(f"User {request.user} is not the author of the post {slug}")
        return render(request, '403.html')
    
    # Fetch the post from the server
    post = Post.objects.get(slug=slug)
    if request.method == 'POST':
        logging.debug(f"POST request on post {slug}")
        form = forms.EditPost(request.POST, request.FILES, instance=post)
        if form.is_valid():
            logging.debug(f"Form is valid")
            form.save()
            return redirect('posts:page', slug=slug)
        
    else:
        form = forms.EditPost(instance=post)
        logging.debug(f"GET request on post {slug}")
    
    return render(request, 'posts/post_edit.html', {'form': form, 'slug': slug})


def post_delete_view(request, slug):
    logging.info(f"Post delete view on post with slug: {slug}")
    # If the request was not done by the autor of the post, return 403
    if request.user != Post.objects.get(slug=slug).author:
        logging.error(f"User {request.user} is not the author of the post {slug}")
        return render(request, '403.html')
    
    post = Post.objects.get(slug=slug)
    post.delete()
    logging.debug(f"Post {slug} deleted")
    return redirect('users:user-posts')

app/posts/templates/posts/all_posts.html
<!--home.html-->
{% extends 'layout.html'%}
{% block title%}
    All Posts
{% endblock %}
{% block content %}
    <div class="container py-4">
        <h1 align="center">Posts List</h1>
        <div class="row mb-2">
            <div class="container-fluid">
                <div class="row">
                    <p>Filter by Category:</p>
                </div>
                <div class="row">
                    <form class="d-flex" method="POST" action="{% url 'posts:filter-view' %}">
                        {% csrf_token %}
                        <select class="form-select me-2" name="select_query">
                            <option value="all">All</option>
                            {% for key, category in categories %}
                                <option value="{{ key }}">{{ category }}</option>
                            {% endfor %}
                        </select>
                        <button class="btn btn-outline-dark" type="submit">Filter</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="container-fluid">
                <form class="d-flex" role="search" method="POST" action="{% url 'posts:search-view' %}">
                    {% csrf_token %}
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search_query">
                    <button class="btn btn-outline-dark" type="submit">Search</button>
                </form>
            </div>
        </div>
        <div class="row" align="center">
            {% for post in posts %}
                <div class="col-xl-6 col-xxl-4 p-2">
                    <div class="card" style="width: 20rem; max-width: 100%;" align="start">
                        <img 
                        src="{{ post.banner.url }}" 
                        alt="Image description"
                        class="card-img-top"/>
                        <div class="card-body">
                            <h2 class="card-title">{{ post.title }}</h2>
                            <p class="card-text">{{ post.date }} by <strong><a href="{% url 'users:profile'  username=post.author.username %}">{{ post.author }}</a></strong></p>
                            <p class="card-text">Category: <strong>{{post.get_category_display}}</strong></p>
                            <p class="card-text text-truncate">{{ post.body }}</p>
                            <a href="{% url 'posts:page' slug=post.slug %}" class="btn btn-dark">Read Full Article</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

app/posts/templates/posts/comment_new.html
{% extends 'layout.html'%}
{% load crispy_forms_tags %}
{% block title%}
    New Comment Page
{% endblock %}
{% block content %}
<div class="container py-4">
    <div class="row d-flex justify-content-center">
        <div class="col-md-8 col-xl-6">
            <div class="card px-5 py-5">
                <h1 class="h3 mb-3 fw-normal">New Post</h1>
                <form
                class="row"
                action="{% url 'posts:new-comment' slug=slug %}" 
                method="POST" 
                enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <button type="submit" class="btn btn-dark">Submit Comment</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/posts/templates/posts/filter_posts.html
<!--home.html-->
{% extends 'layout.html'%}
{% block title%}
    Filtered Posts
{% endblock %}
{% block content %}
    <div class="container py-4">
        {% if query %}
            <h1 align="center"> Posts in the "{{ query }}" Category</h1>
        {% else %}
            <h1 align="center">All Posts</h1>
        {% endif %}
        <div class="row mb-2">
            <div class="container-fluid">
                <div class="row">
                    <p>Filter by Category:</p>
                </div>
                <div class="row">
                    <form class="d-flex" method="POST" action="{% url 'posts:filter-view' %}">
                        {% csrf_token %}
                        <select class="form-select me-2" name="select_query">
                            <option value="all">All</option>
                            {% for key, category in categories %}
                                <option value="{{ key }}">{{ category }}</option>
                            {% endfor %}
                        </select>
                        <button class="btn btn-outline-dark" type="submit">Filter</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="container-fluid">
                <form class="d-flex" role="search" method="POST" action="{% url 'posts:search-view' %}">
                    {% csrf_token %}
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search_query">
                    <button class="btn btn-outline-dark" type="submit">Search</button>
                </form>
            </div>
        </div>
        <div class="row" align="center">
            {% for post in posts %}
                <div class="col-xl-6 col-xxl-4 p-2">
                    <div class="card" style="width: 20rem; max-width: 100%;" align="start">
                        <img 
                        src="{{ post.banner.url }}" 
                        alt="Image description"
                        class="card-img-top"/>
                        <div class="card-body">
                            <h2 class="card-title">{{ post.title }}</h2>
                            <p class="card-text">{{ post.date }} by <strong>{{ post.author }}</strong> </p>
                            <p class="card-text">Category: <strong>{{post.get_category_display}}</strong></p>
                            <p class="card-text text-truncate">{{ post.body }}</p>
                            <a href="{% url 'posts:page' slug=post.slug %}" class="btn btn-dark">Read Full Article</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

app/posts/templates/posts/post_edit.html
{% extends 'layout.html'%}
{% load crispy_forms_tags %}
{% block title%}
    Edit Post
{% endblock %}
{% block content %}
    <div class="container py-4">
    <div class="row d-flex justify-content-center">
        <div class="col-md-8 col-xl-6">
            <div class="card px-5 py-5">
                <h1 class="h3 mb-3 fw-normal">Edit Post</h1>
                <form 
                class="row g-3"
                action="/posts/{{ slug }}/edit/" 
                method="POST"
                enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <button type="submit" class="btn btn-dark me-2 w-100 py-2">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>   
{% endblock %}

app/posts/templates/posts/post_new.html
{% extends 'layout.html'%}
{% load crispy_forms_tags %}
{% block title%}
    New Post Page
{% endblock %}
{% block content %}
<div class="container py-4">
    <div class="row d-flex justify-content-center">
        <div class="col-md-8 col-xl-6">
            <div class="card px-5 py-5">
                <h1 class="h3 mb-3 fw-normal">New Post</h1>
                <form
                class="row"
                action="{% url 'posts:new-post' %}" 
                method="POST" 
                enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <button type="submit" class="btn btn-dark me-2 w-100 py-2">Create Post</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/posts/templates/posts/post_page.html
{% extends 'layout.html'%}
{% block title%}
    {{post.title}}
{% endblock %}
{% block content %}
    <section>
        <div class="container py-4">
            <div class="row">
                <div class="col">
                    <img 
                    src="{{ post.banner.url }}"
                    alt="Image description"
                    class="img-fluid rounded"/>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <h1 align="center">{{post.title}}</h1>
                </div>
                <div class="row p-2">
                    <div class="col">
                        <p>{{post.body}}</p>
                    </div>
                </div>
                <div class="col" align="end">
                    <p>Posted on: <strong>{{post.date}}</strong></p>
                    <p>Written by: <a href="{% url 'users:profile'  username=post.author.username %}">{{ post.author }}</a></p>
                </div>
            </div>
        </div>  
    </section>
    
    <!-- Comments section -->
    <section class="gradient-custom">
        <div class="container my-5 py-5">
            <div class="row d-flex justify-content-center">
                <div class="col-md-12 col-lg-10 col-xl-8">
                    <div class="card">
                        <div class="card-body p-4">
                            <h4 class="text-center mb-4 pb-2">Comments Section</h4>
                            {% for comment in comments %}
                            <div class="row mb-2">
                                <div class="col">
                                    <div class="d-flex flex-start">
                                        <img src="{{ comment.author.userprofile.profile_image.url }}" alt="user profile image" width="65" height="65" class="rounded-circle shadow-1-strong me-3">
                                        <div class="flex-grow-1 flex-shrink-1">
                                            <div>
                                                <div class="d-flex justify-content-between align-items-center">
                                                    <p class="mb-1">
                                                        <a class="link-opacity-10" href="{% url 'users:profile'  username=comment.author.username %}">{{comment.author}}</a> - <span class="small">{{comment.date}}</span>
                                                    </p>
                                                </div>
                                                <p class="small mb-0">
                                                    {{comment.body}}
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                            <div class="row">
                                <a class="btn btn-dark mt-2" href="{% url 'posts:new-comment' slug=post.slug %}">Leave a comment</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

app/posts/templates/posts/search_posts.html
<!--home.html-->
{% extends 'layout.html'%}
{% block title%}
    Searched Posts
{% endblock %}
{% block content %}
    <div class="container py-4">
        {% if query %}
            <h1 align="center">Searched Posts with "{{ query }}"</h1>
        {% else %}
            <h1 align="center">All Posts</h1>
        {% endif %}
        <div class="row mb-2">
            <div class="container-fluid">
                <div class="row">
                    <p>Filter by Category:</p>
                </div>
                <div class="row">
                    <form class="d-flex" method="POST" action="{% url 'posts:filter-view' %}">
                        {% csrf_token %}
                        <select class="form-select me-2" name="select_query">
                            <option value="all">All</option>
                            {% for key, category in categories %}
                                <option value="{{ key }}">{{ category }}</option>
                            {% endfor %}
                        </select>
                        <button class="btn btn-outline-dark" type="submit">Filter</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="container-fluid">
                <form class="d-flex" role="search" method="POST" action="{% url 'posts:search-view' %}">
                    {% csrf_token %}
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search_query">
                    <button class="btn btn-outline-dark" type="submit">Search</button>
                </form>
            </div>
        </div>
        <div class="row" align="center">
            {% for post in posts %}
                <div class="col-xl-6 col-xxl-4 p-2">
                    <div class="card" style="width: 20rem; max-width: 100%;" align="start">
                        <img 
                        src="{{ post.banner.url }}" 
                        alt="Image description"
                        class="card-img-top"/>
                        <div class="card-body">
                            <h2 class="card-title">{{ post.title }}</h2>
                            <p class="card-text">{{ post.date }} by <strong>{{ post.author }}</strong> </p>
                            <p class="card-text">Category: <strong>{{post.get_category_display}}</strong></p>
                            <p class="card-text text-truncate">{{ post.body }}</p>
                            <a href="{% url 'posts:page' slug=post.slug %}" class="btn btn-dark">Read Full Article</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}