app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('about/', views.about),
    path('contact/', views.contact),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.all_posts, name='list'),
    path('new-post/', views.post_new, name='new-post'),
    path('<slug:slug>', views.post_page, name='page'),
    path('search/', views.search_posts, name='search-view'),
    path('filter/', views.filter_posts, name='filter-view'),
    path('<slug:slug>/new-comment/', views.comment_new, name='new-comment'),
    path('<slug:slug>/edit/', views.post_edit_view, name='edit-post'),
    path('<slug:slug>/delete/', views.post_delete_view, name='delete-post'),
]

app/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('update-profile/', views.update_profile_view, name='update-profile'),
    path('profile/<str:username>/', views.profile_view, name='profile'),
    path('user-posts/', views.user_posts_view, name='user-posts'),

]

app/templates/about.html
<!--home.html-->
{% extends 'layout.html'%}
{% block title%}
    About Me
{% endblock %}
{% block content %}
<!-- About 1 - Bootstrap Brain Component -->
<section class="py-4 py-md-5 min-vh-100">
  <div class="container">
    <div class="row gy-3 gy-md-4 gy-lg-0 align-items-lg-center">
      <div class="col-12 col-lg-6 col-xl-5">
        <img class="img-fluid img-thumbnail" loading="lazy" src="../static/assets/Io.jpeg" alt="My picture">
      </div>
      <div class="col-12 col-lg-6 col-xl-7">
        <div class="row justify-content-xl-center">
          <div class="col-12 col-xl-11">
            <h2 class="mb-3">Who Am I?</h2>
            <p class="lead fs-4 text-secondary mb-3">I'm Aleandro Presta, a Software Engineer specialized in Machine Learning and Web Development</p>
            <p class="mb-5">I am a dedicated and enthusiastic software engineer with a master's degree in Artificial Intelligence and Machine Learning. My passion for technology extends beyond my professional career, as I continuously seek to expand my knowledge and skills in the ever-evolving field of software development.</p>
            <div class="row gy-4 gy-md-0 gx-xxl-5X">
              <div class="col-12 col-md-6">
                <h3 align="left">Connect with me:</h3>
                <p align="left">
                <a href="https://linkedin.com/in/aleandro-presta-6523471b9" target="blank" title="My LinkedIn profile"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/linked-in-alt.svg" alt="aleandro-presta-6523471b9" height="30" width="40" /></a>
                <a href="https://github.com/AleandroPresta" target="blank" title="My GitHub profile"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/github.svg" alt="AleandroPresta" height="30" width="40" /></a>
                <a href="mailto: aleandro.presta@outlook.com" target="blank" title="Send me an Email"><img align="center" src="../static/assets/envelope.svg" alt="Email" height="30" width="40" /></a>
                <a href="https://www.frontendmentor.io/profile/AleandroPresta" target="blank" title="My Frontend Mentor profile"><img align="center" src="https://cdn.worldvectorlogo.com/logos/frontendmentor-logo.svg" alt="Email" height="30" width="40" /></a>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

app/templates/contact.html
<!--home.html-->
{% extends 'layout.html'%}
{% block title%}
    Contacts
{% endblock %}
{% block content %}
    <div class="container-fluid py-4 min-vh-100">
        <h1>Contact Me!</h1>
    </div>
{% endblock %}

app/templates/home.html
<!--home.html-->
{% extends 'layout.html'%}
{% block title%}
    Home
{% endblock %}
{% block content %}
<!-- Background image -->
<div id="intro" class="bg-image">
    <div class="mask" style="background-color: rgba(0, 0, 0, 0.8);">
        <div class="container d-flex align-items-center justify-content-center text-center h-100">
            <div class="text-white" data-mdb-theme="dark">
                <h1 class="mb-3">Articles Website</h1>
                <h5 class="mb-4">Register, Login and write Articles</h5>
                {% if user.is_authenticated %}
                    <a class="btn btn-outline-light btn-lg m-2" href="{% url 'posts:list' %}">Posts</a>
                    <a class="btn btn-outline-light btn-lg m-2" href="{% url 'posts:new-post' %}">New Post</a>
                {% else %}
                    <a class="btn btn-outline-light btn-lg m-2" href="{% url 'users:login' %}">Login</a>
                    <a class="btn btn-outline-light btn-lg m-2" href="{% url 'users:register' %}">Sign-up</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{% block title %} Articles Website {% endblock %}</title>
        {% load bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript %}
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg sticky-top bg-dark navbar-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">Articles</a>
                <button
                    class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarToggler"
                    aria-controls="navbarToggler"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                >
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarToggler">
                    <ul class="nav nav-underline">
                        <li class="nav-item">
                            <a class="nav-link" href="/about">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'posts:list' %}">Posts</a>
                        </li>
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'posts:new-post' %}">New Post</a>
                            </li>
                        {% endif %}
                    </ul>
                    {% if user.is_authenticated %}
                    <div class="dropdown dropstart text-end">
                        <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="{{ user.userprofile.profile_image.url }}" alt="user profile image" width="32" height="32" class="rounded-circle">
                        </a>
                        <ul class="dropdown-menu text-small shadow" style="">
                            <li><a class="dropdown-item" href="{% url 'posts:new-post' %}">New Post</a></li>
                            <li><a class="dropdown-item" href="{% url 'users:user-posts' %}">My Posts</a></li>
                            <li><a class="dropdown-item" href="{% url 'users:update-profile' %}">My Profile</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><button type="button" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#logoutModal">
                                Logout
                            </button></li>
                        </ul>
                    </div>
                    {% else %}
                    <div class="text-end">
                        <a class="btn btn-outline-light me-2" href="{% url 'users:login' %}" title="Login a New User">Login</a>
                        <a class="btn btn-warning" href="{% url 'users:register' %}">Sign-up</a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </nav>
        {% block content %} {% endblock %}
        <div class="container sticky-bottom">
            <footer class="py-3 my-4 bd-footer ">
                <ul class="nav nav-underline justify-content-center border-bottom pb-3 mb-3" id="footer">
                    <li class="nav-item">
                        <a class="nav-link px-2 text-body-secondary" href="/about">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link px-2 text-body-secondary" href="/contact">Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link px-2 text-body-secondary" href="{% url 'posts:list' %}">Posts</a>
                    </li>
                </ul>
                <p class="text-center text-body-secondary">&copy; 2024 Aleandro Presta</p>
            </footer>
        </div>

        <!-- Modal -->
        <div class="modal fade" id="logoutModal" tabindex="-1" aria-labelledby="logoutModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="logoutModalLabel">Confirm Logout</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        Are you sure you want to logout?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <form class="logout" action="{% url 'users:logout' %}" method="POST">
                            {% csrf_token %}
                            <button class="btn btn-dark" type="submit">Logout</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </body>
</html>